### ISSUE TITLE
Problem about testing speed results

### ISSUE THREAD

**Issue by Xenooooooooo** [osu-crypto/libOTe#108]
Hello, profrssor. My speed sheet of libOTe is getting closer to completion, and I've got some question about the tests using ./frontend_test.

1. I made the the number of OTs in the test increased by applying ./frontend_test -n 1048576 -u or by changing the numOT param in the code and rebuild the whole project. After that, I've noticed that the IKNP's time remains around 200 ms(COTE) and 450 ms(OTE). 

Is this figure reasonable, or I have to change elsewhere to made it run 2^20 OTs for real?

2. In my test, the IKNP's COTE test is always quicker than softspoken's ROTE. Is this figure reasonable?

3. In my test, VOLE Silent OT's malivious OTE is always quicker that VOLE Silent OT's quasi-cyclic ROTE test. Is this figure reasonable?

Testing Environment: Ubuntu 22.04 LTS (jammy), 4 GB RAM, 60 GB ROM, Intel® Core™ i7-8550U CPU @ 1.80GHz, 4 threads available.

Thanks a lot, professor.

**Comment by ladnir** [comment]
its possible that iknp is now faster. When lance did soft spoken he optimized the "transpose" operations but didn't update IKNP to use the faster version. Since his paper i updated IKNP to use his faster code so now maybe IKNP is faster. I suggest looking at the code as opposed to just hoping you are measuring the right thing.

In order of speed, i think it should be 
* IKNP
* SoftSpoken
* Silent (SIlver codes **EXPERIMENTAL**)
* Silent (EA codes)
* Silent (quasi-cyclic)

**Comment by Xenooooooooo** [comment]
Thanks a lot for your reply about IKNP and softspoken. 

And how about the 3rd question? What I've noticed is that **malicious** VOLE Silent OT is faster than **semi-honest** quasi-cyclic VOLE Silent OT.

Besides, there seems not to have EA codes Silent OT's test interface in the ./UnitTests.h. Is this test be left out?

**Comment by Xenooooooooo** [comment]
Thanks a lot, professor! Your answers are really helpful and inspiring.
