### ISSUE TITLE
Building only Errors

### ISSUE THREAD

**Issue by hkhajeh** [osu-crypto/libOTe#121]
The command python3 build.py --all --boost --sodium yields the following error without any hints for resolution. I have installed all of the required dependencies (I also presumed the build.py automatically install the missing dependencies even if I did not). sudo apt-get install build-essential cmake libssl-dev libgmp-dev git 

============= Building Sodium =============
Checkout 4e825a68baebdf058543f29762c73c17b1816ec0
'/usr/bin/git' 'checkout' '4e825a68baebdf058543f29762c73c17b1816ec0'
HEAD is now at 4e825a68 Merge branch 'master' of github.com:jedisct1/libsodium
Autogen
'./autogen.sh' '-s'
libtoolize: $pkgltdldir is not a directory: `/mingw/share/libtool'
Downloading config.guess and config.sub...
chmod: cannot access 'build-aux/config.guess': No such file or directory
chmod: cannot access 'build-aux/config.sub': No such file or directory
Done.
Configure
'./configure' '--prefix=/home/homa/libOTe/cmake/../out/install/linux' '--with-pic=no'
CMake Error at cryptoTools/thirdparty/fetch.cmake:21 (message):
  Configure failed (No such file or directory).
Call Stack (most recent call first):
  cryptoTools/thirdparty/getSodium.cmake:67 (run)
  cryptoTools/cmake/cryptoToolsDepHelper.cmake:140 (include)
  cryptoTools/CMakeLists.txt:163 (include)

-- Configuring incomplete, errors occurred!
See also "/home/homa/libOTe/out/build/linux/CMakeFiles/CMakeOutput.log".
gmake: Makefile: No such file or directory
gmake: *** No rule to make target 'Makefile'.  Stop.
and command python3 build.py --setup --boost --sodium 
and python3 build.py --all--boost --relic
and

**Comment by ladnir** [comment]
Here is where those commands are coming from https://github.com/ladnir/cryptoTools/blob/master/thirdparty/getSodium.cmake#L57

My guess is that you dont have autotools installed which is required by the sodium build system. Assuming this is the case, your options are:

- install autotools. https://askubuntu.com/questions/430706/installing-autotools-autoconf-on-ubuntu
- use relic instead of sodium. `python23 build.py -DENABLE_RELIC=true -DENABLE_SODIUM=false`.
