### ISSUE TITLE
CoeffCtx for Z_p

### ISSUE THREAD

**Issue by lzjluzijie** [osu-crypto/libOTe#151]
I want to use vole on some $Z_p$ for around 64 bit prime $p$. Is it possible to modify `CoeffCtxInteger` to achieve this? Thank you.

**Comment by ladnir** [comment]
yes. but you might want to give a new impl for `bool isField() {return true;}`.

So say you have 
```
// subfield
struct Zp
{
     u64 value;
     Zp operator+(const Zp) const;
     Zp operator-(const Zp) const;
     Zp operator*(const Zp) const;
     ...
};
// extension field
struct Zpx
{
     std::array<Zp, 2> value;
     
     Zpx operator+(const Zpx) const;
     Zpx operator-(const Zpx) const;
     Zpx operator*(const Zpx) const;
     Zpx operator*(const Zp) const;
     ...
}
```

then `CoeffCtxInt` should just work.

**Comment by lzjluzijie** [comment]
Got it, thank you very much. Do you have any suggestion on how to compute arithmatic operations module p for 64 bit or 128 bit integers? Should I use rejection sampling for `fromBlock`?

**Comment by ladnir** [comment]
For sampling, If your p is close to 2^64, id do rejection sampling.

For example, you can do

```
auto b = seed.get<64>(0) < p;
val = (seed.get<u64>(0) ^ seed.get<u64>(1)) * b ^ seed.get<u64>(1) ;
```
This will select the first 64 bits if it's smaller and otherwise the second. You can compute the pr of this failing. 

If p is close to 128 bits you can just assume it's OK. 

`val=seed`


For arithmetics, not totally sure what's best. Gcc and clang have an int128 type if p is 64 bits. So you could use that and then reduce.

There might be some special purpose code out there that you can use for your specific sizes.

If you want to write it by hand, then you have to break the number into parts and multiple parts, add and then reduce.

**Comment by ladnir** [comment]
maybe this https://github.com/emp-toolkit/emp-zk/blob/master/emp-zk/emp-zk-arith/int_fp.h

**Comment by lzjluzijie** [comment]
Very helpful, thank you so much!
