### ISSUE TITLE
IknpOtExt features about non-block sized message

### ISSUE THREAD

**Issue by athenKing** [osu-crypto/libOTe#33]
@ladnir Hi, It seems that there is no support to reduce or enlarge the message pair size when using IknpOtExt, and currently it supports only block-sized message, what should I do if I want to adapt my non-block sized message pairs?

**Comment by ladnir** [comment]
The basic idea is that the normal OT call output keys. You then use those keys however you want. For example, to encrypt the messages you want to send.

**Comment by athenKing** [comment]
It's true, while in my scenario messages as short as 1 bit is enough, this would significantly reduce the communication cost after performing base OT transfer when m is large, I guess I could try modifying it for my use locally.

**Comment by ladnir** [comment]
There is no need to modify the library itself. Just call the `send(...), receive(...)` functions and the output will be the keys. Then in your own code you can perform the encryption. See the `sendChosen(...), receiveChosen(...)` functions for an example. However, for one bit messages, what you will want to do it one-time-pad encrypt your chosen bit with the least significant bit of the keys,

Also, if you are doing very small messages, you might consider use the SilentOt protocol. Otherwise, IKNP will internally use 128 bits of communication per OT.
