### ISSUE TITLE
Unable to "make install" (mac)

### ISSUE THREAD

**Issue by KuraTheDog** [osu-crypto/libOTe#44]
Main issue: 
When I try make install, I run into it being unable to find a "cryptotools-config.cmake" in cryptotools.

```
[ 96%] Built target libOTe_Tests
[100%] Built target frontend_libOTe
Install the project...
-- Install configuration: "Release"
CMake Error at cryptoTools/cmake_install.cmake:41 (file):
  file INSTALL cannot find
  "/Users/..../libs/libOTe/cryptoTools/cryptotools-config.cmake": No such
  file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)


make: *** [install] Error 1
```

I kinda worked around this by commenting out the line with `install(FILES cryptotools-config.cmake DESTINATION cmake/)` in the cryptoTools/CmakeList.txt. 
But while this does technically get through `make install` without errors, it feels like the wrong thing to do.

------

Possibly related issue: Even after doing the above workaround, I am not sure of the right way to include it in my project.

`find_package(libOTe REQUIRED)` fails, as it can't find "libOTeConfig.cmake" or "libote-config.cmake" anywhere. 
Because of the workaround above, using "cryptoTools" as the name fails for similar reasons.

What is the correct package name? Or am I doing this incorrectly?
I couldn't find any "*onfig.cmake" files in this project that would hint at what I should use. 

---

Some context:
On a mac.
I had to update the libOTE minimum cmake version to get cmake to stop having openmp issues. 
"make" itself is working, to the extent that `./frontend/frontend_libOTe` has output.
I have relic installed, and enabled. I also turned on NP and IKNP just as a baseline. 
I ran things out of a "build" folder, i.e. `mkdir build; cd build; cmake .. {options}; make`.

**Comment by ladnir** [comment]
your fix is the correct one for now. 

For `find_package`, the issue is that install is only partially supported. My current solution is to not do an install and load the cmake files

- https://github.com/osu-crypto/libOTe/blob/master/cmake/libOTeHelper.cmake
- https://github.com/osu-crypto/libOTe/blob/master/cmake/loadCacheVar.cmake

These scripts assume that you either did an in-source build or used the build folder `./out/build/linux`

An example of how to include these is here https://github.com/osu-crypto/libPSI/blob/master/CMakeLists.txt#L123

These two scripts will load the relevant cache variables from libOTe (so you don't have to set them manually) and then defines 

- `libOTe_LIB`
- `libOTe_INC`

At some point, I intend on fully supporting install but I haven't gotten there yet.

**Comment by KuraTheDog** [comment]
Thanks! 
I had to rebuild out of just libOTe, rather than the libOTe/build folder I originally made and ran it out of, for the scripts to find it.
But my project at least seems to be building when I include those two cmake files
(I dont' call it yet, but I'm hopeful)
