### ISSUE TITLE
recent KOS15 vulnerability

### ISSUE THREAD

**Issue by themighty1** [osu-crypto/libOTe#87]
Hi, in light of the recent KOS15 vulnerability, I think it should be disabled in libOTe. At least until the time when the fix is implemented. There is an update to the paper with the fix https://eprint.iacr.org/2015/546

**Comment by ladnir** [comment]
Some mitigations have been put in place. Moreover, the attack does not apply to 128 bit security. However, the security of it does remain unclear. I'll add a warning at least. Plus soft spoken is now there so it can be used instead.

**Comment by themighty1** [comment]
Thank you for your response. Could you pls clarify what was meant by
> the attack does not apply to 128 bit security

Are you saying that KOS15's 128-bit **computational** security remians intact and the attack only decreases the **statistical** security (which the paper suggest be set to 40 bits) ? If so, will it make sense to increase the statistical security to something like 1000 bits in order to provide a margin against a yet-unknown attack.

**Comment by ladnir** [comment]
Added a warning when KOS is used (can be disabled). Also removed KOS usage by silent OT.

Not sure it makes sense to actually fix KOS since soft-spoken is effectively better in all cases. 

If there is an actual need I might be persuaded to implement the soft-spoken malicious checks for KOS. 

Cheers,
Peter

**Comment by ladnir** [comment]
FYI https://eprint.iacr.org/2022/1371
